# tests/verify_phase_6_3.py
# -------------------------
# Automated verification script for Phase 6.3: ChromaDB Integration.

import logging
import os
import sys
import uuid
from fastapi.testclient import TestClient

# Add parent directory to sys.path to allow imports from app
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.main import app
from app.embeddings.chroma_service import ChromaService
from app.embeddings.embedding_service import EmbeddingService
from app.config import settings

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("verify_phase_6_3")


def run_tests():
    logger.info("==========================================================")
    logger.info("STARTING PHASE 6.3 CHROMADB INTEGRATION VERIFICATION")
    logger.info("==========================================================")

    # 1. Verify ChromaService starts up correctly
    logger.info("Step 1: Instantiating and initializing ChromaService...")
    chroma_service = ChromaService()
    health = chroma_service.health_check()
    logger.info(f"ChromaDB Health: {health}")
    assert health["status"] == "healthy", "ChromaDB connection is unhealthy!"

    # 2. Setup Test User via API
    logger.info("\nStep 2: Registering a test user...")
    client = TestClient(app)
    suffix = uuid.uuid4().hex[:6]
    email = f"user_{suffix}@ekip-test.com"
    password = "SecurePassword123!"

    reg_response = client.post("/api/auth/register", json={"email": email, "password": password})
    assert reg_response.status_code == 201, f"Registration failed: {reg_response.text}"
    user_id = reg_response.json()["id"]

    # Login to obtain JWT
    logger.info("Step 3: Logging in to obtain JWT...")
    login_response = client.post("/api/auth/login", json={"email": email, "password": password})
    assert login_response.status_code == 200
    token = login_response.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}

    # 4. Upload and process a document
    logger.info("\nStep 4: Uploading and processing test document...")
    file_content = (
        "Enterprise Knowledge Intelligence Platform uses vector search.\n\n"
        "ChromaDB stores embeddings generated by sentence-transformers models."
    )
    upload_response = client.post(
        "/api/upload",
        files={"file": ("placement_guide.txt", file_content, "text/plain")},
        headers=headers
    )
    assert upload_response.status_code == 201
    doc_id = upload_response.json()["document_id"]
    
    # Process text extraction
    client.post(f"/api/upload/{doc_id}/process", headers=headers)

    # 5. Chunk the document (this triggers generate_batch_embeddings and add_documents in Chroma)
    logger.info("\nStep 5: Chunking document to trigger embedding storage...")
    chunk_response = client.post(f"/api/upload/{doc_id}/chunk", headers=headers)
    assert chunk_response.status_code == 200
    total_chunks = chunk_response.json()["total_chunks"]
    logger.info(f"Chunk response: Chunks generated: {total_chunks}")

    # 6. Verify vector storage in ChromaDB
    logger.info("\nStep 6: Querying ChromaDB directly to verify stored embeddings...")
    info = chroma_service.get_collection_info()
    logger.info(f"Collection Info: {info}")
    initial_total_items = info["total_items"]
    assert initial_total_items >= total_chunks, f"Expected at least {total_chunks} items, found {initial_total_items}"

    # Verify query returns expected metadata keys: owner_id, filename, document_id, chunk_id
    # We generate a mock query embedding of size 384
    query_emb = [0.1] * settings.EMBEDDING_DIMENSION
    search_results = chroma_service.similarity_search(
        query_embedding=query_emb,
        n_results=1,
        where={"document_id": doc_id}
    )
    assert len(search_results["ids"][0]) > 0
    metadata = search_results["metadatas"][0][0]
    logger.info(f"Retrieved Metadata: {metadata}")
    assert metadata["document_id"] == doc_id
    assert metadata["owner_id"] == user_id
    assert metadata["filename"] == "placement_guide.txt"
    assert "chunk_id" in metadata
    logger.info("✓ Document metadata keys (document_id, chunk_id, owner_id, filename) verified.")

    # 6.5. Verify API Search Endpoint
    logger.info("\nStep 6.5: Testing /api/search API endpoint...")
    api_search_response = client.post(
        "/api/search",
        json={"query": "vector search and embeddings", "top_k": 3},
        headers=headers
    )
    assert api_search_response.status_code == 200, f"Search failed: {api_search_response.text}"
    search_data = api_search_response.json()
    assert search_data["query"] == "vector search and embeddings"
    assert len(search_data["results"]) > 0
    result_chunk = search_data["results"][0]
    assert "document_id" in result_chunk
    assert "chunk_id" in result_chunk
    assert "score" in result_chunk
    assert "text" in result_chunk
    assert "metadata" in result_chunk
    assert result_chunk["metadata"]["filename"] == "placement_guide.txt"
    assert result_chunk["metadata"]["owner_id"] == user_id
    logger.info("✓ Search API response format and metadata verified.")

    # 7. Reprocessing Check
    logger.info("\nStep 7: Testing document reprocessing (deleting old vectors and recreating)...")
    rechunk_response = client.post(f"/api/upload/{doc_id}/chunk", headers=headers)
    assert rechunk_response.status_code == 200
    
    info_after = chroma_service.get_collection_info()
    assert info_after["total_items"] == initial_total_items, "Item count mismatch after re-chunking!"
    logger.info("✓ Idempotent reprocessing check passed (old vectors purged and replaced).")

    # 8. Cleanup
    logger.info("\nStep 8: Cleaning up test documents...")
    client.delete(f"/api/upload/{doc_id}", headers=headers)
    
    info_final = chroma_service.get_collection_info()
    expected_final_count = initial_total_items - total_chunks
    assert info_final["total_items"] == expected_final_count, f"Vectors were not deleted from ChromaDB! Expected {expected_final_count}, found {info_final['total_items']}"
    logger.info("✓ Vector cleanup verified successfully.")

    logger.info("\n==========================================================")
    logger.info("ALL PHASE 6.3 STEP 3 INTEGRATION TESTS PASSED SUCCESSFULLY!")
    logger.info("==========================================================")


if __name__ == "__main__":
    try:
        run_tests()
    except AssertionError as ae:
        logger.error(f"Verification Assertion failed: {ae}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        sys.exit(1)
