# app/schemas/conversation.py
# -------------------------
# Pydantic validation schemas for chat conversations and message payloads.

from datetime import datetime
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class ChatMessageCreate(BaseModel):
    """
    Schema for creating a new message.
    """
    role: str = Field(..., description="Role of the sender: USER, ASSISTANT, or SYSTEM")
    content: str = Field(..., description="Content text of the message")
    token_count: Optional[int] = Field(None, description="Number of tokens in message text")
    model_name: Optional[str] = Field(None, description="Model identifier if generated by AI")
    metadata_json: Optional[Dict[str, Any]] = Field(None, description="Custom metadata options")


class ChatMessageResponse(BaseModel):
    """
    Serialization schema for messages.
    """
    id: int
    conversation_id: int
    role: str
    content: str
    token_count: Optional[int]
    model_name: Optional[str]
    response_time_ms: Optional[int]
    metadata_json: Optional[Dict[str, Any]]
    created_at: datetime

    model_config = {
        "from_attributes": True
    }


class ConversationCreate(BaseModel):
    """
    Schema for initializing a new empty conversation.
    """
    workspace_id: Optional[int] = Field(None, description="Target workspace ID for conversation partitioning")
    title: Optional[str] = Field(None, description="Thread subject title")


class ConversationResponse(BaseModel):
    """
    Detailed serialization schema for conversations including messages thread list.
    """
    id: int
    uuid: str
    workspace_id: int
    user_id: int
    title: Optional[str]
    is_pinned: bool
    is_archived: bool
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    messages: List[ChatMessageResponse] = []

    model_config = {
        "from_attributes": True
    }


class ConversationSummary(BaseModel):
    """
    Summarized serialization schema for conversation list items.
    """
    id: int
    uuid: str
    workspace_id: int
    title: Optional[str]
    is_pinned: bool
    is_archived: bool
    created_at: datetime
    updated_at: datetime

    model_config = {
        "from_attributes": True
    }


class ConversationListResponse(BaseModel):
    """
    Paginated conversations list wrapper.
    """
    items: List[ConversationSummary]
    page: int
    page_size: int
    total_records: int
    total_pages: int


class ConversationDeleteResponse(BaseModel):
    """
    Outcome schema for deletion requests.
    """
    success: bool
    message: str


class ConversationRenameRequest(BaseModel):
    """
    Payload schema to change conversation title.
    """
    title: str = Field(..., min_length=1, max_length=255)


class ConversationPinRequest(BaseModel):
    """
    Payload placeholder for pin requests.
    """
    pass


class ConversationArchiveRequest(BaseModel):
    """
    Payload placeholder for archive requests.
    """
    pass


class ConversationSearchRequest(BaseModel):
    """
    Search request parameters.
    """
    keyword: str
    page: Optional[int] = 1
    page_size: Optional[int] = 20


class ConversationSearchItem(BaseModel):
    """
    Summarized search match item displaying message count.
    """
    id: int
    uuid: str
    workspace_id: int
    title: Optional[str]
    is_pinned: bool
    is_archived: bool
    message_count: int
    created_at: datetime
    updated_at: datetime

    model_config = {
        "from_attributes": True
    }


class ConversationSearchResponse(BaseModel):
    """
    Paginated search output.
    """
    items: List[ConversationSearchItem]
    page: int
    page_size: int
    total_records: int
    total_pages: int


class PinnedConversationResponse(BaseModel):
    """
    List wrapper for pinned conversations.
    """
    items: List[ConversationSummary]


class ArchivedConversationResponse(BaseModel):
    """
    List wrapper for archived conversations.
    """
    items: List[ConversationSummary]
